### ISSUE TITLE
repeat ayah

### ISSUE THREAD

**Issue by ali-ghamdan** [0xzer0x/quran-companion#102]
### The type of the feature request

Recitation

### The feature request

repeat verse or some verses (like Ayah app in android) or Ayat.
it will be good, + if you can add الحصري (قصر) will be good

**Comment by 0xzer0x** [comment]
> repeat verse or some verses (like Ayah app in android) or Ayat.

Repeating a set of verses is already available in the player since [v1.2.7](https://github.com/0xzer0x/quran-companion/releases/tag/v1.2.7).

> if you can add الحصري (قصر)

Could you please clarify? `الحصري (قصر)` is already available in the reciters drop-down.
