### ISSUE TITLE
crashed at certain surah when audio is played

### ISSUE THREAD

**Issue by HattaPauzi** [0xzer0x/quran-companion#113]
### The problem

I am listening to Surah Ar-Rahman in which the reciter is Mishary Alafasy. All of a sudden when it reaches to the end of verse 16 it crashed... This happens consistently at that exact verse...
This is the video recording of what happened...
https://github.com/user-attachments/assets/6a8e015c-b233-4e4d-af59-eece362f8b38

### Release version

Version 1.3.1

### Operating system

Arch Linux x86_64

### Steps to reproduce the behavior

1. Go to Surah Ar-Rahman
2. Play it before verse 16 of the surah by reciter named Mishary Alafasy
3. and then it crashed

### Log files

[Mon Nov 12 17:49:40 2024][CRITICAL] verseIdxInPage is out of page coords range!!!  file:  line: 0
[Mon Nov 11 17:49:40 2024][DEBUG] "file 019001.mp3 is missing."  file:  line: 0

### Additional context

after seeing the log files, maybe redownloading the reciter would work. I'll give it a try... or maybe just copy and rename a same file of that verse. thanks maintainer.

**Comment by HattaPauzi** [comment]
nope, redownload the recitation did not work, checked the 019001.mp3, it is from a different surah

**Comment by 0xzer0x** [comment]
It seems to be an issue with the QCF v2 font, I tested it with QCF v1 and the issue does not occur. I will look into it. Thanks for the detailed issue description.

**Comment by 0xzer0x** [comment]
It is due to differences between the QCF v1 and v2 fonts, should be fixed in 5d01fe8.

**Comment by HattaPauzi** [comment]
thanks, so after it being merged to the main branch I can update it from the AUR? sorry if I am asking a stupid question, i am new to this, just curios on how the AUR works...

**Comment by 0xzer0x** [comment]
Yes, it should be fixed in version 1.3.2.
