### ISSUE TITLE
Surah's will cut and change to something else without playing to the end. 

### ISSUE THREAD

**Issue by ezvision** [0xzer0x/quran-companion#13]
I've noticed this issue on quite a few surahs around the end of the quran, for example surah 93.

It will play half-way through but then randomly stop before it reaches the end and skip to a different surah.

I'm using Nassar Alqatami as a reciter. 

This part isn't a bug, but I also have a request to have Yusuf Ali's translation added. It's one of my favorites and one of the most popular ones.

**Comment by 0xzer0x** [comment]
As-salamu alaykum Brother,
Thanks for pointing out the issue. It was due to improper detection of the last verse in the page. It was checking only the number of the ayah not the surah number which caused this unexpected behavior. This issue should now be fixed. Please let me know if it persists.

**Comment by ezvision** [comment]
Wa-alaikum salaam,

I went through some of the surahs and the issue seems to be fixed now. I'll let you know if I notice it again.

Thank you for the quick fix.
