### ISSUE TITLE
Bug: Zoom out also zooms in

### ISSUE THREAD

**Issue by K1ngfish3r** [0xzer0x/quran-companion#15]
To reproduce
Right click on page -> Zoom out

Expected
Zoom out

Result
Zoom in

System specs
Ryzen 5 3500U
Windows 11
Installed through:  qc_online_installer_x64_win.exe

Also tested on
Intel i5 12600k
Fedora 38
Installed through: Flatpak

I cant stop zooming in help

**Comment by 0xzer0x** [comment]
As-salamu alaykum,
I found out that this bug affects only pages 1 & 2. It will be fixed in the next release inshallah. thanks for reporting it.

**Comment by 0xzer0x** [comment]
Fixed in #19 v1.1.8

**Comment by K1ngfish3r** [comment]
I can confirm I can no longer come across this issue
