### ISSUE TITLE
Feature Request: Double page view

### ISSUE THREAD

**Issue by K1ngfish3r** [0xzer0x/quran-companion#16]
Would like to hide the translation and get a full double page spread.

System specs
Intel i5 12600k
Installed through: Flatpak

**Comment by 0xzer0x** [comment]
As-salamu alaykum,
Added the feature in #19 v1.1.8

**Comment by K1ngfish3r** [comment]
Walykum salam,
Not really a bug, but its kinda awkward when right click lets you set zoom for one page at a time. Setting font size in the preferences gets around this.
Would like to request the following feature(s)
Additional Right click option: Set font size
Shortcut to adjust font size (eg: ctrl + scroll up/down like in chrome)

**Comment by 0xzer0x** [comment]
In double page mode, the right click menu doesn't adjust the size of both pages as many QCF v2 pages and some QCF v1 pages are disproportionate and require manual adjustment of one of the pages so I didn't want to completely remove the ability to adjust only one of the pages but there is the settings workaround you mentioned to adjust both pages.
