### ISSUE TITLE
Snap package on Snapcraft.io

### ISSUE THREAD

**Issue by RasheedAZ** [0xzer0x/quran-companion#20]
Jazaakallaahu khairan for this useful app. Can you please package it as a Snap and publish on Snapcraft for Ubuntu and its official flavours? 

I love Flatpak and Appimage and use them on my PC but our school PCs run Ubuntu and only Snaps run OK without issues.

**Comment by 0xzer0x** [comment]
As-salamu alaykum,
I have managed to get it to work as a snap. seems to work fine on ubuntu but let me know if you face any issues with it. https://snapcraft.io/quran-companion

**Comment by RasheedAZ** [comment]
> As-salamu alaykum, I have managed to get it to work as a snap. seems to work fine on ubuntu but let me know if you face any issues with it. https://snapcraft.io/quran-companion

Wa alaikumussalaam and jazaakallaahu khairan. Working fine except that the download gets stuck most of the time but I think that's because of our bad internet connection.
