### ISSUE TITLE
Changes to the UX/UI for easier studying

### ISSUE THREAD

**Issue by ibrahim-mu** [0xzer0x/quran-companion#43]
### The feature request

I've been looking for an app for my Quranic studies on Linux, and I'm glad I found this app today.
I can see that the layout is very good for reading, but I'm wondering if another layout for studying is possible.
I usually need to check different interpretations or translations, but changing the interpretations is a manual process each time. Can there be a layout for people who need to quickly browse different interpretations and translations and maybe search them?
And thank you for the great app.

### Proposed solution

A fourth layout for interpretations and translations

**Comment by 0xzer0x** [comment]
> quickly browse different interpretations and translations

I have an alternative solution for this, It would be done through a combobox for changing between different additional content displayed in the tafsir dialog, so switching between them is easier. Like in the image below

![mockup](http://0x0.st/Hd2Z.png)

**Comment by hazemk537** [comment]
good idea
