### ISSUE TITLE
Having problem downloading Al-Baqarah recitation by Mishary Alafasy

### ISSUE THREAD

**Issue by mahdihasan2006** [0xzer0x/quran-companion#49]
### The problem

I don't think it's a bug of the app but the download of Al-Baqarah recitation by Mishary Alafasy fails near the end. That didn't happened with other surah's or reciters.

### Release version

Version 1.2.3 (flatpak)

### Operating system

Fedora Linux 39 (Workstation Edition)

### Steps to reproduce the behavior

1. Go to download manager.
2. Add Al-Baqarah recitation by Mishary Alafasy to queue.
3. The download fails at the very end.

### Log files

[Sat Feb 24 08:19:31 2024][WARNING] Couldn't load VAAPI library  file:  line: 0
[Sat Feb 24 08:19:31 2024][CRITICAL] verseIdxInPage is out of page coords range!!!  file:  line: 0

### Screenshots

![Screenshot from 2024-02-24 06-50-32](https://github.com/0xzer0x/quran-companion/assets/121625152/62e4acc3-3a64-4938-b3c5-980173e4f3fc)
![Screenshot from 2024-02-23 08-58-25](https://github.com/0xzer0x/quran-companion/assets/121625152/ae020c58-7ce6-4e55-b11c-4f9b09dbb324)

### Additional context

I think using GitHub discussion for taking about these problems will be better.

**Comment by 0xzer0x** [comment]
Seems to be an issue with the flatpak package only, I will try to investigate this further. As an temporary solution, I suggest using the appimage until I find out the root cause of this issue. 

Thanks for reporting.
