### ISSUE TITLE
Move audio controls to the sidebar

### ISSUE THREAD

**Issue by benomaire** [0xzer0x/quran-companion#51]
I assume most users use their screen in the landscape mode, so it is probably a good idea to save some screen real estate for the Quran page to get the font size slightly larger.

**Comment by 0xzer0x** [comment]
As-salamu alaykum,
Have you considered using the "Toggle player controls" shortcut? It hides the player completely so the reader can take up the whole page.

**Comment by benomaire** [comment]
Oh. I didn't know that!
But there is no UI control so I did not expect to find a shortcut for a functionality without a UI control.
You may consider adding a button next to the `Navigation` button, or a checkbox toggle in the `view` menu.

Still the Quran page does not rescale, it remains the same size.
