### ISSUE TITLE
Lost all translations

### ISSUE THREAD

**Issue by ezvision** [0xzer0x/quran-companion#54]
### The problem

As-salamu alaykum

Sometime around the past few releases (I believe when you redid the ui colors) I've lost access to all english translations except the clear quran. I also don't have any option to see any tafseers other than the arabic al-sa'ady

### Release version

latest version

### Operating system

fedora 39, but my friend on windows 11 has the same issue.

### Screenshots

![Screenshot at 2024-03-25 23-50-08](https://github.com/0xzer0x/quran-companion/assets/31146313/72faf9f8-c952-409c-a7d6-03249a5eda71)
![Screenshot at 2024-03-25 23-50-33](https://github.com/0xzer0x/quran-companion/assets/31146313/5445ec8f-6a70-4c1a-944a-758830cb0ea3)

### Additional context
I'm using the flatpak version of the app and have deleted and reinstalled it too, the issue still remains.

**Comment by 0xzer0x** [comment]
Walaikum Assalam,

The tafasir and translations have been moved out of the application bundle and are **available to download through the downloads manager**. Tafasir and translations should appear automatically once downloaded.

**Comment by ezvision** [comment]
ty
