### ISSUE TITLE
Error building on yay arch linux 

### ISSUE THREAD

**Issue by Airbus5717** [0xzer0x/quran-companion#55]
### The problem

i get this error 

```
CMake Error at CMakeLists.txt:29 (add_subdirectory):
  The source directory

    /home/airbus/.cache/yay/quran-companion-git/src/quran-companion/third_party/QtAwesome

  does not contain a CMakeLists.txt file.

```

the command i ran is `yay -S quran-companion-git`

### Release version

1.2.1-1

### Operating system

Linux airbus 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux

**Comment by 0xzer0x** [comment]
Should be fixed now. However, I recommend using the binary release package `quran-companion` instead of `quran-companion-git` as it's more compact than cloning the entire repository.
