### ISSUE TITLE
adding more tafsir books

### ISSUE THREAD

**Issue by zeyadelkholyttt** [0xzer0x/quran-companion#56]
### The feature request

need more tafsir books like ibn kasir and al tabari and moso3at el qera2at and other books which in online resources like quran.com or other quran sites

### Proposed solution

u can add some way to make the program detect the book source and try to match it with ayat

**Comment by 0xzer0x** [comment]
As-salamu alaykum,

Tafsir Ibn-Kathir, Al-Tabary, and other tafasir **can be downloaded through the download manager under the 'Tafsir' list**.

**Comment by zeyadelkholyttt** [comment]
aha thx, it will be more clear if the other tafasir added to the tafsir menu and send me notification to download it if i changed the tafsir to it (cuz his place in the reads very hidden)

**Comment by 0xzer0x** [comment]
Created #57 for tracking the UI issue. Will be closing this one now.
