### ISSUE TITLE
إضافة ترجمة bridges foundation

### ISSUE THREAD

**Issue by omardoescode** [0xzer0x/quran-companion#72]
### The feature request

إضافة ترجمة bridges foundation

### Proposed solution

this translation is very good already and carefully written

**Comment by 0xzer0x** [comment]
Unfortunately, this is not possible due to Copyright reasons. The following disclaimer is from the [official Bridges foundation website](https://bridges-foundation.org/product/bridges-translation-of-quran/).

> Warning: Duplicating or copying this file for others is a violation of religion, law and moralities because countless hours and finances have been invested to produce it and illegal duplication jeopardizes future productions of this kind.
