### ISSUE TITLE
Add a repeat function for the player  memorizing Quran

### ISSUE THREAD

**Issue by zayedalsaidi** [0xzer0x/quran-companion#78]
### The feature request

Please add a repeat function for the player (for a range of Ayats) similar to this:
https://www.nquran.com/ar/quranplayer/

### Proposed solution

https://www.nquran.com/ar/quranplayer/

**Comment by zayedalsaidi** [comment]
@0xzer0x thank you for your effort. Today, I have chance to check the version 1.2.7 on Linux (Flatpak). Unfortunately, the repeat button does not work.  Do I miss something here?

**Comment by 0xzer0x** [comment]
Just tested the Flatpak version and seems to be working fine. Maybe try the [AppImage](https://github.com/0xzer0x/quran-companion/releases/download/v1.2.7/Quran_Companion-1.2.7-x86_64.AppImage) and check if the issue persists?

**Comment by zayedalsaidi** [comment]
Still same issue. 

![image](https://github.com/0xzer0x/quran-companion/assets/18646956/da515177-3db4-44f1-ae85-7e2a7e76d555)

**Comment by zayedalsaidi** [comment]
To be precise, when I press the repeat button I don't get the RepeaterPopup
widget. So, nothing get repeated 😔

في الاثنين، ٢٤ يونيو ٢٠٢٤، ١٠:٠٩ م Youssef Fathy ***@***.***>
كتب:

**Comment by 0xzer0x** [comment]
Probably an issue with the popup widget positioning on screen. The positioning seems to have inconsistent behavior on Windows. Will look into it.

**Comment by 0xzer0x** [comment]
Apparently it is due to positioning the repeater widget using screen coordinates not the parent widget coordinate system. Should be fixed in 434cbf8

**Comment by 0xzer0x** [comment]
Please give [v1.2.8 AppImage](https://github.com/0xzer0x/quran-companion/releases/download/v1.2.8/Quran_Companion-1.2.8-x86_64.AppImage) a try and let me know if the issue is still present.

**Comment by zayedalsaidi** [comment]
It's working flawlessly under Linux. Thank you.
