### ISSUE TITLE
البحث بكلمات الآي

### ISSUE THREAD

**Issue by AbdulmajedAhmad** [0xzer0x/quran-companion#89]
### The feature request

السلام عليكم ورحمة الله، وبعد: فجزاكم الله خيرًا على هذا التطوير النافع والذي اعتنى بنظام تشغيل مهجور نسبيًا لدى المطورين العرب.

**أما الميزة** فهي: أن يمكن البحث عن أية آية بكلمة (أو جزء منها كأن تبحث بـ:"_ستعين_" فتظهر لك آية فيها "_نــستعين_") أو كلمات، على أن **يهمل** البحث الحركات والتشكيل للتسهيل.

**نتيجة البحث**: عرض الآيات المتضمنة للنص المبحوث، وعند النقر على إحداها: يفتح البرنامج الصفحة من المصحف ويظلل الآية المبحوثة.

### Proposed solution

أظن البرنامج يحوي (يخزن في ذاكرته) الآيات نصًا، ولكن إن لم يكن كذلك فيمكن البحث على الشبكة عن القرآن كاملًا ملفًا نصيًا (جرب: whole Quran as text)، مثل هذا المشروع ([Tanzil | تنزيل](https://tanzil.net/download)).

يشر الله دربكم وفتح عليكم.

**Comment by 0xzer0x** [comment]
وعليكم السلام ورحمة الله وبركاته،

خاصية البحث موجودة بالفعل يمكن الوصول إليها عن طريق:
- اختصار <kbd>f</kbd> (يمكن تخصيصه من خلال نافذة الإعدادات)
- من الشريط العلوي (`عرض->البحث`)
