### ISSUE TITLE
Content: separate extras repository

### ISSUE THREAD

**Issue by 0xzer0x** [0xzer0x/quran-companion#94]
### The type of the feature request

Application

### The feature request

- [x] Move all downloadable extra content to a separate repository
- [x] Update extras download URL in source code

**Comment by hussein-mourad** [comment]
Asslam Alikum

Check out [git lfs](https://git-lfs.com/).
I think it is a good solution to this problem

**Comment by hussein-mourad** [comment]
السلام عليكم ورحمه الله وبركاته
I suggest using [git lfs](https://git-lfs.com/).
TLDR
1. Install git lfs from your package manage
2. Run `git lfs install`  inside the repo
3. Run `git lfs track "*.filetype"
4. Commit and push

- Then you can you this link to download them: 
github.com/\<USERNAME\>/\<REPO\>/raw/\<BRANCH\>/\<FILEPATH\>

**Comment by 0xzer0x** [comment]
وعليكم السلام ورحمة الله وبركاته

Git LFS has limited bandwidth quota, so it is not suitable for this use case since the quota would run out quickly and users would be stuck with 20 KB/s download speed.

Reference: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota

**Comment by hussein-mourad** [comment]
شكراً جزيلا، جزاك الله خير
