### ISSUE TITLE
Missing word on the verse

### ISSUE THREAD

**Issue by zh-hl** [0xzer0x/quran-companion#95]
### The problem

Surah Al-Kahf : 80
Both the reader, and the translation window is showing blank word.

### Release version

1.2.9

### Operating system

MacOS

### Screenshots

![image](https://github.com/user-attachments/assets/acdeb746-7def-4a26-8c7c-f2042a7d5db9)

**Comment by 0xzer0x** [comment]
Seems to be a macOS-only issue. It seems to be an issue in rendering of that word in QCFv1 font. I will be looking further into it. As a temporary solution, you could use the **QCFv2** font for the mushaf page.

**Linux**
![screenshot_2024-08-27_15-19-49](https://github.com/user-attachments/assets/adee6ae1-548f-4fed-9fd2-bec29ae91279)

**Windows**
![windows_1](https://github.com/user-attachments/assets/26dd1e6e-9335-4403-9ecc-c1368155c292)

**Page font setting**
![screenshot_2024-08-27_15-53-11](https://github.com/user-attachments/assets/fb1e2188-de19-4222-b882-77dc859f6e12)
 
**QCFv2**
![screenshot_2024-08-27_15-55-52](https://github.com/user-attachments/assets/e0c082a9-ecf9-4354-aac6-f9dba2fe1820)

**Comment by 0xzer0x** [comment]
It was an issue with the QCFv1 page 302 font file. Fixed in cd3cb91886271b5e9c314510cfe8884041cc742f.
